In [ ]:
import numpy as np

In [1]:
import numpy as np
a1 = np.arange(10, 21)
print(a1)

[10 11 12 13 14 15 16 17 18 19 20]


In [3]:
import numpy as np
a1 = np.arange(10, 51)
a1.shape, a1[:5], a1[-5:]



((41,), array([10, 11, 12, 13, 14]), array([46, 47, 48, 49, 50]))

In [4]:
a2 = np.zeros(10, dtype=int)
a2[4] = 99
a2
print(a2)

[ 0  0  0  0 99  0  0  0  0  0]


In [5]:
a3 = np.random.randint(1, 101, size=15)
a3, a3.min(), a3.max()


(array([69, 87,  6, 36, 35, 67,  9, 68, 42, 72, 97, 57, 24,  7, 71]), 6, 97)

In [6]:
a = np.array([1,2,3,4,5])
a_plus_10 = a + 10
a_times_2 = a * 2
a_squared  = a ** 2
a_mean, a_sum, a_std = a.mean(), a.sum(), a.std()
a_plus_10, a_times_2, a_squared, (a_mean, a_sum, a_std)


(array([11, 12, 13, 14, 15]),
 array([ 2,  4,  6,  8, 10]),
 array([ 1,  4,  9, 16, 25]),
 (3.0, 15, 1.4142135623730951))

In [7]:
a5 = np.arange(1, 21)
odds = a5[a5 % 2 == 1]
odds


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [8]:
a6 = np.arange(10)
rev6 = np.flip(a6)
rev6


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [9]:
a7 = np.random.randint(1, 101, size=20)
a7[a7 > 50] = 0
a7


array([ 5, 35,  0,  0, 24,  0,  0,  0, 18,  4, 14, 22, 14,  0, 32,  0,  7,
       21, 49,  4])

In [10]:
a8 = np.array([2,5,9])
diff8 = np.diff(a8)
diff8


array([3, 4])